version: "#{build}"
clone_depth: 50
image: Visual Studio 2017

environment:
  VISUAL_STUDIO_PATH: "%ProgramFiles(x86)%\\Microsoft Visual Studio\\2017\\Community"
  VISUAL_STUDIO_VERSION: "2017"
  NINJA_VERSION: "1.8.2"
  NINJA_ZIP: "ninja-win.zip"
  NINJA_DOWNLOAD_URL: "https://github.com/ninja-build/ninja/releases/download"

  matrix:
    - platform: x86
      system: "i686-windows"
    - platform: x64
      system: "x86_64-windows"

init:
  - set PATH=%UserProfile%\bin;C:\msys64\usr\bin;%PATH%
  # Make Visual Studio command line tools available
  - call "%VISUAL_STUDIO_PATH%\VC\Auxiliary\Build\vcvarsall.bat" %platform%

install:
  - mkdir "%UserProfile%\bin"
  - curl -fsSL -o "%NINJA_ZIP%" "%NINJA_DOWNLOAD_URL%/v%NINJA_VERSION%/%NINJA_ZIP%"
  - unzip "%NINJA_ZIP%"
  - move ninja.exe "%UserProfile%\bin"
  - del "%NINJA_ZIP%"

build_script:
  - make

after_build:
  - 7z a -tzip "out\Release\gn-%system%.zip" "%APPVEYOR_BUILD_FOLDER%\out\Release\gn.exe"

branches:
  except:
    - chromium-gn
    - google-gn

artifacts:
  - path: out\Release\gn-$(system).zip

deploy:
  - provider: GitHub
    auth_token:
      secure: X4RRj5dZX/U3bEW5KLR3byTbeQpIZCaTwlow+UVFjehhgMysJoi0bYm98Boe3ZPp
    artifact: /gn-.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
