language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - system="i686-linux"
        - DEPLOY=1
    - os: linux
      dist: xenial
      env:
        - system="x86_64-linux"
        - DEPLOY=1
    - os: osx
      osx_image: xcode8
      env:
        - system="x86_64-darwin"
        - DEPLOY=0
    - os: osx
      osx_image: xcode8.3
      env:
        - system="x86_64-darwin"
        - DEPLOY=1
    - os: osx
      osx_image: xcode9
      env:
        - system="x86_64-darwin"
        - DEPLOY=0

before_install:
  - source .travis/setenv.sh

script:
  - make

branches:
  except:
    - chromium-gn
    - google-gn

notifications:
  email: false

before_deploy:
  - tar -C out/Release -czf "out/Release/gn-${system}.tar.gz" gn

deploy:
  provider: releases
  api_key:
    secure: 0p08qDWiTnhIS3v81zaFL/OQNgsSkhDtCl56fUP5X7nE7pbeX7M2w+49L0h74YMdrSwe1abGsUcoZh7Q8w8suxSY6/cHxADBcbclGz88ukahWX9WXJ9fLfrqKkAHNAyGXdtR1G7UUHp8V6isXLYnM9zuG3/8V2HRV+jtSGHOBoTseJYvpJqLy3YZeIAQbrLkckuotDIasOP/S0/OomXYMeP51401LeRzyiGljsv2R1hO2OFfssfAoI5ZcAmMg/igUIhgSPmBzu9K91wnhfu1kaI7RaciL9YZIVOMDGB7KoxpVRnTItwKjlltNa9EIs4PZWqKoVhGYjGKeCtnaJatvK7cVD5o/eqwMSBXg82WN1CJaMDc5rlLcXuyNC4a5kHUYHdyY4tP/zTh2pBWk+tV10zJDZc8lw/6kqs44OoxRJSPtl6faiqrwsoVRxLUw22/xTLLRUbpXixyu7NxfprGMdPVxzArVt8CZwfSZ7mZKs+hNx2ZUax6p3TnoDfDTlgzU4PEpcRO+wbNTjVKIl3ywcaBJHiB8gjuDzCuGGQPHAcF2NwBv/ZgJmr6eWtgaplcRxbcqGsFDAkJoPdRwOgK/zIdcTYFyldepTCFm1cocQn/rkXZOUwzt49J1AB3UaXmzdthscO1rLcI6zzRwWBAAKocuzxryJX02oKn6xMDksc=
  file: "out/Release/gn-*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: o-lim/generate-ninja
    tags: true
    condition: $DEPLOY = 1
