// Generated by build/write_buildflag_header.py
// From "buildflag_header"

#ifndef BASE_CFI_FLAGS_H_
#define BASE_CFI_FLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CFI_CAST_CHECK() (0)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_TRAP() (0)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_DIAGNOSTIC() (0)

#endif  // BASE_CFI_FLAGS_H_
